
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: customers_info_model
    description: "A starter dbt model"
    columns:
      - name: c_custkey
        description: "The primary key for customers table"
        tests:
          - unique
          - not_null
      - name: o_custkey
        description: "The primary key for orders table"
        tests:
          - unique
          - not null
  - name: order_status_group_sum
    dscription: "total sum of each group from status"
    columns:
      - name: o_orderstatus
        description: "order status"
     